version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-atomspace
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/atomspace123
      
      # Memory settings
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=512m
      
      # APOC Plugin (correct format for Neo4j 5.x)
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      
      # CSV import settings
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_server_directories_import=import
      
      # Performance
      - NEO4J_server_default__listen__address=0.0.0.0

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: